# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kfD96H19UUq1IKRTdQAbN9vmXpxMtMDo
"""

import pandas as pd
import numpy as np
# Create a pandas DataFrame with numpy random values
data = np.random.rand(4, 4)
df = pd.DataFrame(data, columns=['Feature1', 'Feature2', 'Feature3', 'Feature4'])
print(df)

# Rename the columns of the DataFrame 'df'
df.columns = ['Random value 1', 'Random value 2', 'Random value 3', 'Random value 4']
print(df)

# Get descriptive statistics of the DataFrame 'df'
df.describe()

print(df.isnull().sum())
print(df.dtypes)

import pandas as pd
import numpy as np

# Create a sample dataframe
data = np.random.randint(5, 30, size=(10, 3))
df = pd.DataFrame(data, columns=['Random value 1', 'Random value 2', 'Random value 3'])

# Generate random indices to select values from col2 and col3
v = df[['Random value 2', 'Random value 3']].values
ix = np.random.randint(0, v.shape[1], df.shape[0])

# Create a new column 'value' with random values from col2 or col3
df['value'] = np.take_along_axis(v, ix[:, None], 1)

# Display the resulting dataframe
print(df)

"""# New section"""